dist: trusty
language: python
python:
- '3.6.1'
install:
- pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "thomasschuetz"
    token:
      secure: $SONARCUBE

script:
  - pytest --cov-report xml --cov=src
  - sonar-scanner -X
